spring:
  data:
    mongodb:
      username: alphou
      password: alphou
      hostname: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8032
