spring:
  data:
    mongodb:
      username: alphou
      password: alphou
      address: 192.168.154.250
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8032
